version: "3"

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  
  chat-service:
    image: hienpham95/chat-web-api
    ports:
      - "5000:80"
    build:
      context: ./chat-services
      dockerfile: Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Server=db; UserId=root;Password=123456;Database=chat-app"
      IdentityServerOptions__Authority: http://identity-service
      RedisSettings__Host: redis
      RedisSettings__Password: 123456
    depends_on:
      - db
      - redis

  identity-service:
    image: hienpham95/chat-identity-service
    ports:
      - "5001:80"
    build:
      context: ./identity-server
      dockerfile: Dockerfile
    environment:
      NamedHttpClientFactories__0__BaseAddress: http://chat-service
      ConnectionStrings__DefaultConnection: "Server=db; UserId=root;Password=123456;Database=chat-identity"
      ClientConfigs__BaseAddress: http://localhost:8080

    depends_on:
      - db
  
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass 123456
    hostname: redis
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
